---
AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Role
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: "/"
      Policies:
      - PolicyName: CloudwatchLogs
        PolicyDocument:
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:GetLogEvents
            - logs:PutLogEvents
            Resource:
            - arn:aws:logs:*:*:*
            Effect: Allow
          - Action:
            - ec2:Start*
            - ec2:Stop*
            Resource: "*"
            Effect: Allow
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com