---
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates sns
Parameters:
  Email:
    Description: Subscription to sns
    Type: String
Resources:
  SNS: 
    Type: "AWS::SNS::Topic"
    Properties: 
      Subscription: 
        - 
          Endpoint: 
            Ref: Email
          Protocol: email
      TopicName: failovertopic


