---
AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket to hold the lambda code
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of S3 bucket 
  
