---
AWSTemplateFormatVersion: '2010-09-09'
Description: security group
Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: pilotlight-sg
      GroupDescription: Enable HTTP 
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
Outputs:
  WebServerSecurityGroup:
    Description: sg-id
    Value: !GetAtt WebServerSecurityGroup.GroupId